- name: Unregister subscription
  ignore_errors: yes
  command: subscription-manager remove --all
- name: Unregister subscription
  ignore_errors: yes
  command: subscription-manager remove --all
- name: Attach to gluster pool
  ignore_errors: yes
  command: subscription-manager attach --pool={{ subscription_pool_id }}
- name: enable gluster repos
  command: subscription-manager repos --enable=rh-gluster-3-for-rhel-7-server-rpms
