# Subscripe all nodes to Gluster storage subsctiption
- hosts: nodes
  gather_facts: false
  vars_files:
    - ../all
  serial: 1
  roles:
    - { role: gluster_subscribe }

# Prepare nodes that are using Gluster storage
- hosts: nodes
  gather_facts: false
  vars_files:
    - ../vars.yml
  roles:
    - { role: gluster_prereqs_client }

# Prepare nodes that are running Gluster storage
- hosts: "{{storage_hosts_for_ansible}}"
  gather_facts: false
  vars_files:
    - ../vars.yml
  roles:
    - { role: gluster_prereqs_node }

# Install Gluster storage from first master
- hosts: masters[0]
  gather_facts: false
  vars_files:
    - ../vars.yml
  roles:
    - { role: gluster_prereqs_deploy }
    - { role: gluster_install}

# Subscribe all nodes back to Openshift subscription
- hosts: nodes
  gather_facts: false
  vars_files:
    - ../vars.yml
  serial: 1
  roles:
    - { role: ocp_subscribe, openshift_installation_type == "enterprise" }
