---
- name: Copy SSH key to all hosts
  hosts: all
  become: false
  vars_prompt:
  - name: username
    prompt: Remote user
    default: root
    private: no
  - name: key_file
    prompt: SSH public key
    default: ~/.ssh/id_rsa.pub
    private: no
  tasks:
  - name: Add key to authorized_keys
    authorized_key:
      user: "{{username}}"
      state: present
      key: "{{ lookup('file', key_file) }}"
  - name: Run ssh-keyscan to add keys to known_hosts
    local_action: shell ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
